import { AppBar, Box, Button, Toolbar, Typography } from "@mui/material";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rizzume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box sx={{ flexGrow: 1 }}>
          <AppBar position="fixed" style={{ background: "#2E3B55" }}>
            <Toolbar>
              <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                Rizzume
              </Typography>
              <Button variant="outlined" color="primary">
                Login
              </Button>
            </Toolbar>
          </AppBar>
        </Box>

        {children}
      </body>
    </html>
  );
}
